[package]
name = "client"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = ".."
edition = "2021"
publish = false

[dependencies]
shared = { path = "../shared" }

clap = { version = "=4.4", features = ["derive"] }
bincode = { version = "1.3" }