[package]
name = "shared"
version = "0.1.0"
authors = ["connorcarpenter <connorcarpenter@gmail.com>"]
workspace = ".."
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
